version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
    driver: local
