version: '3.8'
services:
  postgres_main:
    image: postgres:latest
    container_name: postgres_container_main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./main/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./main/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      my_custom_network:
        ipv4_address: 172.30.0.10

  postgres_async:
    image: postgres:latest
    container_name: postgres_container_async
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      my_custom_network:
        ipv4_address: 172.30.0.11

  postgres_sync:
    image: postgres:latest
    container_name: postgres_container_sync
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      my_custom_network:
        ipv4_address: 172.30.0.12

  postgres_async_after_sync:
    image: postgres:latest
    container_name: postgres_async_after_sync
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      my_custom_network:
        ipv4_address: 172.30.0.13

volumes:
  postgres_data:
    driver: local
networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
